### ISSUE TITLE
High risk of SQL injection

### ISSUE THREAD

**Issue by ngiddings** [NerdyMunchkin/itocdc-2015-www#10]
Wherever user input is correlated with an SQL query, whether it be in a form or in the URL, there are no limitations to what the user can put in and there are no checks for integrity. The input is put directly into the corresponding SQL statement.

For example, when a user logs in the program must query the database for the specified information. In that query the email and password given by the user are inserted as clauses into the SQL. If the user's input was an SQL clause to drop the database, the web app would have no issue about that.

There are instances where SQL injection is not a threat due to the nature of the query, such as during registration, but many more are serious security threats to our web app.

**Comment by BEASTLYMONKEY27** [comment]
https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet
I found an SQL prevention cheat sheet, I want to get on it as soon as possible, but there are many places where these problems are evident, so more to fix it the merrier.

**Comment by ngiddings** [comment]
I just got done rewriting all the SQL queries and merging my work into the master branch. I believe the risk of SQL injection is greatly alleviated. Integrity checks will help as well, but that is a different issue.
I am going to close this for now, and if we find later that there is still a risk here we can reopen it.
