### ISSUE TITLE
Password confirmation field in registration doesn't actually check for identical passwords

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#12]
```
if(document.registration.confirm-password.value.length==0){
    alert("Passwords do not match!");
    return false;
}
```

This block doesn't actually check that the fields are identical; it checks that `confirm-password` contains ≥1 character.

**Comment by BEASTLYMONKEY27** [comment]
This issue should now be fixed, I just set the files to try to equal each other, if they don't it returns false. Thus Echoing "Passwords do not match"
