### ISSUE TITLE
Users may only stay logged in for an hour at a time

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#14]
```
setcookie("PHPSESSID", authenticated_session($email), time()+3600);
setcookie("user", $email, time()+3600);
```

These lines create the cookie, and mark it to be deleted in only one hour. This would be inconvenient for users who would like to stay logged in for longer than that.

**Comment by ngiddings** [comment]
We might be able to reset the expiration time to an hour from the current time upon each page load while the user is authenticated. That way, sessions expire after an hour of inactivity.

**Comment by ngiddings** [comment]
This is not a pressing issue, but if I get a chance I'll come up with a system to fix this.

**Comment by ngiddings** [comment]
I fixed it; it was easier than I thought.
