### ISSUE TITLE
User Cookie Security 

### ISSUE THREAD

**Issue by BEASTLYMONKEY27** [NerdyMunchkin/itocdc-2015-www#15]
Can change the cookies to become someone else by using their email
Line 22 Register.php

**Comment by ngiddings** [comment]
I believe I've fixed this with my changes in the authentication branch. We'll have to verify this when we go to test. If it works, this issue can be closed.

**Comment by ngiddings** [comment]
On second thought, we should close this so it's more clear what needs done.
