### ISSUE TITLE
Accounts may be created with the same email or username as an existing account

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#16]
During registration, it is never checked whether or not the username or email is already in use; register.php blindly creates a new record for the new user.

**Comment by ngiddings** [comment]
One of the fundamental rules of DB development is that each value in the key column must be unique. In this case, the key for each row in the user table is the user's email. SQL with naturally give errors if you attempt a non-unique email.

Usernames, on the other hand, can be unique, which creates some issues with being able to identify other members.

Passwords can obviously be unique.

**Comment by ngiddings** [comment]
Made a patch on the registration branch.
