### ISSUE TITLE
Proper User Input

### ISSUE THREAD

**Issue by BEASTLYMONKEY27** [NerdyMunchkin/itocdc-2015-www#18]
Integrity Problems, with user inputs when characters such as ; are used, followed by a command

**Comment by ngiddings** [comment]
I've begun to fix this. I added some integrity checks that can ensure that a string is a valid email, and check for non-alphanumeric characters. I haven't been able to do this for all code yet, though.

**Comment by ngiddings** [comment]
I added a few more checks. My changes are on the integrity-checks branch. I fixed everything I've seen, but someone will need to review my work.

**Comment by ngiddings** [comment]
Jordan, I'm going to have you review my work. I need you to ensure that sufficient checks are done on both client and server side code.
