### ISSUE TITLE
Uploaded files are not checked for file type until after they're put into the permanent directory

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#20]
When files are uploaded, they are moved to the permanent directory, _then_ checked for filetype. Then, if the file has an invalid filetype, an error is thrown, but nothing is actually done with the file.

**Comment by ngiddings** [comment]
This is the most serious issue we've found so far, in my opinion. It should be a simple fix, but I am working on finishing SQL query security. I'm going to assign this issue to Jimmy.

**Comment by ngiddings** [comment]
I did it for you, Jimmy. I rearranged all the checks so that uploads cannot be made unless you are logged in and the file has the proper extension. This issue has to be left open since the branch with my patch has not been tested.

**Comment by ngiddings** [comment]
On second thought, we should close this so it's more clear what needs done.
