### ISSUE TITLE
Uploaded files are only checked for filetype, not for file contents.

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#21]
When a file is uploaded, only the filetype is checked for validity; the file itself can contain anything without throwing an error.

**Comment by ngiddings** [comment]
Added the bug label to this. People having the ability to upload arbitrary data is a relatively serious security threat.

**Comment by ngiddings** [comment]
Jimmy, I'm assigning you to fix this issue. You've looked further into it than everyone else.

**Comment by ngiddings** [comment]
You have other work to do at this point. I'm switching this issue to Clayton.
