### ISSUE TITLE
Do users have direct access to the raw video files?

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#22]
Can a user navigate to the directory where videos are stored and do a directory listing/download individual files from there?

**Comment by ngiddings** [comment]
I would say no. If we've done our other hardening tasks correctly there should be no way for an outside user to query our database for a full listing of videos, and access to the file is only indirect. If the file is in the database, an HTML video tag is used to embed it.

Video scraping is a pretty complicated issue and although the current set of proposed patches don't fix it they do deter the problem fairly well. I'm going to close this, as I don't think the issue or solution is greatly relevant to the web front end at this point.
