### ISSUE TITLE
Should filesize be measured in MiB or MB?

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#23]
`fileSize = fileSize / 1048576; //size in mb`
From post.php, lines 78 and 81.
This is currently being measured in mibibytes (2^20 bytes), not megabytes (10^6 bytes). Wouldn't megabytes be a more accurate, understandable representation of the actual filesize?

**Comment by ngiddings** [comment]
My vote would be MiB. Most software uses MiB, except for instances like hardware manufacturing where you want an overestimate. We should probably just leave the file measurement as it is.
