### ISSUE TITLE
Video Length < 4

### ISSUE THREAD

**Issue by BEASTLYMONKEY27** [NerdyMunchkin/itocdc-2015-www#24]
Upload.php
Line 59
`shell_exec("ffmpeg -i \"$uploadDir/$filename\" -ss 00:00:04 -f image2 -s qvga \"$uploadDir/$shortname.png\"");`

What if video length is < 4?
Run test to check for sure, change time?

**Comment by ngiddings** [comment]
If this is an issue, you'll be working on it Clayton.
