### ISSUE TITLE
Potential bash injection threat

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#26]
File: upload.php, line 60
`shell_exec("ffmpeg -i \"$uploadDir/$filename\" -ss 00:00:04 -f image2 -s qvga \"$uploadDir/$shortname.png\"");`
If `$filename` contains certain characters, bash injection could occur.

**Comment by ngiddings** [comment]
Could somebody try and demonstrate that this is a real issue? Perhaps upload a file with a name that could compromise the shell command, and see the result on the server. If this isn't verified by Friday, I'm going to close it.

**Comment by ngiddings** [comment]
With my rearranging of video upload checks, this issue has been fixed. Rather than taking the original filename for this command, the shortname is used. This means that the user cannot directly give input to this command.
