### ISSUE TITLE
User doesn't need to be logged in to view user profiles.

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#29]
User profile pages are viewable by anybody, regardless of whether or not the viewer is logged in.

**Comment by ngiddings** [comment]
This, along with other issues, may be fixed by my new authentication system. Testing will prove this, but for now we can consider it done.

Let's not close the issue until it's proven fixed.

**Comment by ngiddings** [comment]
A subset of user information is public, namely posted videos. It's things like contact info that must be kept private.
