### ISSUE TITLE
Videos play automatically, but the player GUI does not reflect that.

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#42]
When a video page is loaded, the video plays automatically, but the "play" button doesn't disappear from the center of the player, and the progress bar doesn't move.

**Comment by ngiddings** [comment]
Ech, isn't software great? I'll put Jordan on this.

**Comment by ngiddings** [comment]
At this point this issue isn't worth it, I'm going to close it.
