### ISSUE TITLE
Untrusted Connection errors about 50% of the time upon page load.

### ISSUE THREAD

**Issue by jummy0** [NerdyMunchkin/itocdc-2015-www#48]
Because our security certificate is self-signed, modern browsers will throw an "Untrusted Connection" error at users about half the time they load a page. Adding a security exception only works temporarily.

**Comment by majiru** [comment]
This itself is a problem just because I used two different certificates for haproxy so that it thinks the certificate is being reset when it jumps server connections.  All of this will be fixed with the inclusion of a signed certificate we are hoping to receive sometime in the near future.

**Comment by majiru** [comment]
Now that proper certs are issued and configured this should never be the case anymore.
