### ISSUE TITLE
Application Database User has to many privileges 

### ISSUE THREAD

**Issue by njohnsn** [NerdyMunchkin/itocdc-2015-www#49]
Consider recreating Application Database User with only SELECT, INSERT, UPDATE, and DELETE privileges on the tables it needs access to. 

This will prevent possible attempts to DROP or TRUNCATE tables in case a SQL injection attack is successful.

**Comment by majiru** [comment]
As of currently the cdc user which is what we use for the web code only has the SELECT, INSERT, and UPDATE privileges for the database that we use. I left off DELETE as it wasn't being in any of the php code as of now.

**Comment by ngiddings** [comment]
I believe this issue is already fixed, so I'm going to close it.

If my understanding of our network is correct, the DB is not connected to the competition network so no one outside of our network can query it, and it has only the minimum operations allowed, so we should be okay in this regard.
