### ISSUE TITLE
Bootstrap library is out of date.

### ISSUE THREAD

**Issue by njohnsn** [NerdyMunchkin/itocdc-2015-www#50]
Bootstrap is a javascript library that is being used to create the website's User Interface.

The version on the website is 3.0.3. The latest is 3.4.3 @ http://getbootstrap.com

I would consider upgrading to the latest version.

**Comment by ngiddings** [comment]
This is your end of the workflow, Jacob. I don't know if you want to do this yourself or have Nathan and Jimmy work on it, but I'm going to assign it to you so that I know not to worry about it.
