### ISSUE TITLE
Verify file size in php code, not just in JS code.

### ISSUE THREAD

**Issue by njohnsn** [NerdyMunchkin/itocdc-2015-www#59]
MAX_SIZE form parameter can be spoofed.

**Comment by ngiddings** [comment]
This is a relatively big issue, as we can easily lose our allotted resources to this vulnerability.

Clayton, I'll assign this to you. This is higher priority than other usability issues.

**Comment by BEASTLYMONKEY27** [comment]
I think we now got a max file size worked out

**Comment by majiru** [comment]
File size is now checked in php along with it being part of the max_file_upload ini settings.
