### ISSUE TITLE
Sanitize "message" parameter sent back to forms

### ISSUE THREAD

**Issue by njohnsn** [NerdyMunchkin/itocdc-2015-www#63]
To prevent HTML/PHP injection attack

**Comment by ngiddings** [comment]
Messages are sent to other pages often, along with other parameters. There aren't many that are sanitized right now; our main focus has been direct user input.

Clayton, I'm going to assign this issue to you. You need to review each page and make sure that parameters are sanitized before use.

**Comment by ngiddings** [comment]
Done!
