### ISSUE TITLE
Fatal error in Terms and Privacy

### ISSUE THREAD

**Issue by ngiddings** [NerdyMunchkin/itocdc-2015-www#64]
When loading the terms or privacy page, a fatal error is reported. It reads:

Fatal error: Call to undefined function is_authenticated() in /var/www/privacy.php on line 55

This may just be a typo or missing include, but this is still critical; errors like this are unacceptable this close to the competition.

**Comment by BEASTLYMONKEY27** [comment]
Well I made a change, I tried including authenticate.php maybe the function will run now. Otherwise i'm not too sure

**Comment by majiru** [comment]
Now has the proper include, was missing sessions.php
