### ISSUE TITLE
Finicky session handler

### ISSUE THREAD

**Issue by ngiddings** [NerdyMunchkin/itocdc-2015-www#65]
The session handling system behaves strangely. I'm not sure how else to describe this. My experience in as follows:

I login and am redirected to the homepage as an authenticated session. After clicking a single like, I am logged out. I go to log back in, and I get a message saying 'Already logged in elsewhere'. After trying again I can log in, and the session behaves as expected.

**Comment by ngiddings** [comment]
After properly logging out and logging back in again, I got a 'Logged in elsewhere' error the first time. It seems to take two attempts to log in at all.

**Comment by majiru** [comment]
This is due to session sickness with the load balancer, this can be resolved with a small use of cookies via haproxy

**Comment by majiru** [comment]
Session Sickness is now fixed, HAProxy now locks a user to one server for 60m at a time.
