### ISSUE TITLE
Bizarre video post failure

### ISSUE THREAD

**Issue by ngiddings** [NerdyMunchkin/itocdc-2015-www#66]
When I go to post a video, I can do so without any error given. After filling out the form and submitting, however, I am redirected to Jacob's video that has been here for days. My video does not show up on the home screen.

**Comment by ngiddings** [comment]
We need to explore this further by analyzing the database and code, and repeating this with many accounts and video files.

**Comment by majiru** [comment]
This was due to incorrect information being passed to the hashing algorithm, this has now been fixed.
