### ISSUE TITLE
Password security requirements

### ISSUE THREAD

**Issue by ngiddings** [NerdyMunchkin/itocdc-2015-www#8]
As far as I know, we are allowed to implement a standard for passwords within our web service (not on the server itself). The routine to create a new account only mandates that you don't leave the password field blank.   We could improve user security by implementing an algorithm to judge the security of a user's password and select a minimum for it to be accepted.

This routine could be as simple as a minimum string length or requiring numbers or symbols, and it could be as complex as estimating Kolmogorov complexity for the given string. Either way, we would benefit from having some type of standard for user passwords.

**Comment by BEASTLYMONKEY27** [comment]
Password requirement is now a minimum of 6 characters, we can strengthen this later but for now it's better than what we had.
