### ISSUE TITLE
Logout button will not always work

### ISSUE THREAD

**Issue by ngiddings** [NerdyMunchkin/itocdc-2015-www#9]
When the logout button is clicked, a php file is loaded that clears the session value in the 'PHPSESSID' cookie, and reduces its expiration time by one hour. If the cookie's expiration time was to be modified after creation, the logout butting would fail to work.

In addition to that, the 'user' cookie is never touched by the logout routine. That means that the account the user was logged into can be discovered, compromising their privacy.

My solution would be to ensure that when 'logout.php' is run, both cookies are permanently deleted.

**Comment by jummy0** [comment]
Marked as invalid; user is always logged out as the cookie's time is set to 3600s before the _current_ time, not the time on the cookie.

**Comment by ngiddings** [comment]
Assuming you've fixed your error in the logout button, I can't find a reason to keep this open.
